### ISSUE TITLE
Adding contributors breaks HTML header style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-csd#74]
Without contributors:

<img width="924" alt="Screen Shot 2019-03-20 at 11 16 59 AM" src="https://user-images.githubusercontent.com/11865/54656722-bc6fba00-4b01-11e9-9d8e-c21e000ab563.png">

With contributors:

<img width="917" alt="Screen Shot 2019-03-20 at 11 15 51 AM" src="https://user-images.githubusercontent.com/11865/54656725-c0034100-4b01-11e9-9dde-eeb58518fdc1.png">

Problem: the generated HTML is missing a tag around the contributor area:
<img width="718" alt="Screen Shot 2019-03-20 at 11 07 18 AM" src="https://user-images.githubusercontent.com/11865/54656745-d27d7a80-4b01-11e9-9e25-412843c2b379.png">

But the processing code that deals with it seems correct... (except for the `<div class="affiliation">` where I don't know where it came from)

<img width="799" alt="Screen Shot 2019-03-20 at 11 07 23 AM" src="https://user-images.githubusercontent.com/11865/54656765-e7f2a480-4b01-11e9-85a2-481cc564f901.png">

**Comment by opoudjis** [comment]
I've fixed the HTML, but it still doesn't look like yours: the blue background in both cases goes all the way down to the Foreword (it is an attribute of the wrapper of the whole title section). So in fact it was intended to look like that.

**Comment by ronaldtse** [comment]
No its not — the blue is only supposed to look like the first image. There is a missing close tag.
