### ISSUE TITLE
Integrate repo contents into `metanorma-csd`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-csd#79]
This repo is supposed to be read by the `metanorma new` command:

* When the user types `metanorma init -t csd --doctype=standard my-doc` (or something similar) it should duplicate the `standard/` template directory to `my-doc` (creating the directory).

* All files from `common/` in this repository should also be copied into the `my-doc` destination directory. (except when a files to copy, is already existing in the template, for which we ignore that file)

* In order to support offline generation of documents, we can `git submodule` this template repository into `metanorma-csd` gem, so that we can still generate new documents from these templates even when the computer is offline.

@abunashir I believe this needs to be split into different tickets elsewhere. Can you help do that too? Thanks!

**Comment by opoudjis** [comment]
@ronaldtse is this ticket still active?

**Comment by ronaldtse** [comment]
No longer active, this has been implemented using https://github.com/metanorma/mn-templates-csd. The 3rd point (offline template generation) however is not implemented. Will send to new ticket.
