### ISSUE TITLE
Term ref sourcing failed in CSD due to `bibitem` typo (should be `bibitemid`)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-csd#86]
Trace. This is identical to the `bibitemid` "typo" we had in the other gem (https://github.com/metanorma/isodoc/issues/117) that was supposed to have fixed by https://github.com/metanorma/metanorma-standoc/commit/14f9d04e626bc52a130532597a4b1835f2fb181e .

<img width="427" alt="Screen Shot 2019-09-10 at 12 00 06 PM" src="https://user-images.githubusercontent.com/11865/64583157-89c4c100-d3c2-11e9-8d50-bd2e5e160dae.png">

```ruby
====== #<Nokogiri::XML::Element:0x3fe6b5840bbc name="eref" namespace=#<Nokogiri::XML::Namespace:0x3fe6d5f165e8 href="https://www.calconnect.org/standards/csd"> attributes=[#<Nokogiri::XML::Attr:0x3fe6b5840414 name="bibitem" value="CCSTD">]>
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
TypeError: no implicit conversion of nil into String
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/inline.rb:87:in `+'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/inline.rb:87:in `eref_parse'
```

Can we ensure that all gems have this issue fixed? Thanks.

**Comment by ronaldtse** [comment]
@opoudjis this fix is apparently not released... It's breaking all documents that source terms. We need to add a rspec for term sourcing in `metanorma-standoc`.

**Comment by opoudjis** [comment]
Released
